param (
    [string]$ProjectDir
)

$envPath = Join-Path $ProjectDir "..\.env"
if (-not (Test-Path $envPath)) {
    Write-Error "No .env file found at $envPath"
    exit 1
}

$secret = ""
$url = ""

Get-Content $envPath | ForEach-Object {
    $line = $_.Trim()
    if ($line.StartsWith("#") -or $line -eq "") { return }
    
    if ($line -match "^OVERLAY_SYNC_SECRET_HEX\s*=\s*(.*)") {
        $secret = $Matches[1].Trim().Trim('"').Trim("'")
    }
    elseif ($line -match "^OVERLAY_SYNC_BASEURL\s*=\s*(.*)") {
        $url = $Matches[1].Trim().Trim('"').Trim("'")
    }
}

if ([string]::IsNullOrEmpty($secret) -or [string]::IsNullOrEmpty($url)) {
    Write-Error "Could not parse OVERLAY_SYNC_SECRET_HEX or OVERLAY_SYNC_BASEURL from .env file"
    exit 1
}

$key = [System.Text.Encoding]::UTF8.GetBytes("RUST+DESK")
$secretBytes = [System.Text.Encoding]::UTF8.GetBytes($secret)
$urlBytes = [System.Text.Encoding]::UTF8.GetBytes($url)

$encSecret = New-Object byte[] $secretBytes.Length
for ($i=0; $i -lt $secretBytes.Length; $i++) {
    $encSecret[$i] = $secretBytes[$i] -bxor $key[$i % $key.Length]
}

$encUrl = New-Object byte[] $urlBytes.Length
for ($i=0; $i -lt $urlBytes.Length; $i++) {
    $encUrl[$i] = $urlBytes[$i] -bxor $key[$i % $key.Length]
}

$secretStr = ($encSecret | ForEach-Object { "0x{0:x2}" -f $_ }) -join ", "
$urlStr = ($encUrl | ForEach-Object { "0x{0:x2}" -f $_ }) -join ", "

$code = @"
// <auto-generated />
namespace RustPlusDesk.Services.Data
{
    public static class ObfuscatedSecrets
    {
        public static readonly byte[] ObfuscationKey = new byte[] { 0x52, 0x55, 0x53, 0x54, 0x2b, 0x44, 0x45, 0x53, 0x4b }; // "RUST+DESK"
        public static readonly byte[] ObfuscatedSecret = new byte[] { $secretStr };
        public static readonly byte[] ObfuscatedUrl = new byte[] { $urlStr };
    }
}
"@

$outputPath = Join-Path $ProjectDir "Services\Data\ObfuscatedSecrets.cs"
$outputDir = Split-Path $outputPath
if (-not (Test-Path $outputDir)) {
    New-Item -ItemType Directory -Force -Path $outputDir | Out-Null
}

[System.IO.File]::WriteAllText($outputPath, $code)
Write-Host "Generated obfuscated secrets successfully at $outputPath"
